// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFbvLbab_QF91tHSp_ZOQNRq_-Uxq8qgA',
    appId: '1:1002512677601:web:24a4ca7fc5edcaafc815a0',
    messagingSenderId: '1002512677601',
    projectId: 'healthweb-a4064',
    authDomain: 'healthweb-a4064.firebaseapp.com',
    storageBucket: 'healthweb-a4064.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-swKUf2knlK1pwaNG-zOapua1RVIq1vo',
    appId: '1:1002512677601:android:8f70599d92ed4755c815a0',
    messagingSenderId: '1002512677601',
    projectId: 'healthweb-a4064',
    storageBucket: 'healthweb-a4064.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0QUPGlVdL1SDotqXiRG4UeLsNZ3Wh5aA',
    appId: '1:1002512677601:ios:335ec6b3ff850507c815a0',
    messagingSenderId: '1002512677601',
    projectId: 'healthweb-a4064',
    storageBucket: 'healthweb-a4064.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0QUPGlVdL1SDotqXiRG4UeLsNZ3Wh5aA',
    appId: '1:1002512677601:ios:335ec6b3ff850507c815a0',
    messagingSenderId: '1002512677601',
    projectId: 'healthweb-a4064',
    storageBucket: 'healthweb-a4064.firebasestorage.app',
    iosBundleId: 'com.example.driverApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFbvLbab_QF91tHSp_ZOQNRq_-Uxq8qgA',
    appId: '1:1002512677601:web:6a22dbfa0542b5bec815a0',
    messagingSenderId: '1002512677601',
    projectId: 'healthweb-a4064',
    authDomain: 'healthweb-a4064.firebaseapp.com',
    storageBucket: 'healthweb-a4064.firebasestorage.app',
  );
}
